# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m5AlYkxgVAdUxIF-_nl3AIMLEdWxDqb6
"""


from JSON_Crawler import get_last, get_info, get_urls
import time

result = get_urls(get_last())
to_json = get_info(result)

now = time.strftime("%Y-%m-%d")


def toJson(to_json):
    with open('/home/ubuntu/'+now+'.json', 'w', encoding='utf-8') as file:
        json.dump(to_json, file, ensure_ascii=False, indent='\t')


toJson(to_json)
